version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    container_name: facebook_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_MULTIPLE_DATABASES: facebook_auth,facebook_user,facebook_post,facebook_comment,facebook_reaction
    ports:
      - "5432:5432"
    volumes:
      - ./docker-postgres-init:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: 