server:
  port: 8080

spring:
  application:
    name: apiGateway
  cloud:
    gateway:
      routes:
        - id: authService
          uri: http://auth-service:8081
          predicates:
            - Path=/auth/**
        - id: userService
          uri: http://user-service:8082
          predicates:
            - Path=/users/**
        - id: socialGraphService
          uri: http://social-graph-service:8083
          predicates:
            - Path=/friendships/**
        - id: contentService
          uri: http://content-service:8084
          predicates:
            - Path=/posts/**, /postComments/**, /postTags/**
        - id: groupService
          uri: http://group-service:8085
          predicates:
            - Path=/groups/**, /groupMembers/**
        - id: messagingService
          uri: http://messaging-service:8086
          predicates:
            - Path=/conversations/**, /conversationMembers/**, /conversationMessages/**
        - id: eventService
          uri: http://event-service:8087
          predicates:
            - Path=/events/**, /eventAttendees/**