server.port=8080
spring.application.name=apiGateway

# Auth Service Route
spring.cloud.gateway.routes[0].id=authService
spring.cloud.gateway.routes[0].uri=http://auth-service:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/auth/**

# User Service Route
spring.cloud.gateway.routes[1].id=userService
spring.cloud.gateway.routes[1].uri=http://user-service:8082
spring.cloud.gateway.routes[1].predicates[0]=Path=/users/**,/moderator/**

# Social Graph Service Route
spring.cloud.gateway.routes[2].id=socialGraphService
spring.cloud.gateway.routes[2].uri=http://social-graph-service:8083
spring.cloud.gateway.routes[2].predicates[0]=Path=/relationships/**

# Content Service Route
spring.cloud.gateway.routes[3].id=contentService
spring.cloud.gateway.routes[3].uri=http://content-service:8084
spring.cloud.gateway.routes[3].predicates[0]=Path=/posts/**,/comments/**

# Group Service Route
spring.cloud.gateway.routes[4].id=groupService
spring.cloud.gateway.routes[4].uri=http://group-service:8085
spring.cloud.gateway.routes[4].predicates[0]=Path=/groups/**

# Messaging Service Route
spring.cloud.gateway.routes[5].id=messagingService
spring.cloud.gateway.routes[5].uri=http://messaging-service:8086
spring.cloud.gateway.routes[5].predicates[0]=Path=/messages/**

# Event Service Route
spring.cloud.gateway.routes[6].id=eventService
spring.cloud.gateway.routes[6].uri=http://event-service:8087
spring.cloud.gateway.routes[6].predicates[0]=Path=/events/**
