server.port=8080
spring.application.name=apiGateway

eureka.client.enabled=false
spring.cloud.discovery.enabled=false
spring.cloud.service-registry.auto-registration.enabled=false
spring.cloud.gateway.discovery.locator.enabled=false
spring.autoconfigure.exclude=org.springframework.cloud.netflix.eureka.EurekaClientAutoConfiguration

# Comment out the lb:// routes as they require Eureka
# spring.cloud.gateway.routes[0].id=authService
# spring.cloud.gateway.routes[0].uri=lb://AUTH-SERVICE
# spring.cloud.gateway.routes[0].predicates[0]=Path=/auth/**

# spring.cloud.gateway.routes[1].id=userService
# spring.cloud.gateway.routes[1].uri=lb://USER-SERVICE
# spring.cloud.gateway.routes[1].predicates[0]=Path=/users/**,/moderator/**

# spring.cloud.gateway.routes[2].id=socialGraphService
# spring.cloud.gateway.routes[2].uri=lb://SOCIAL-GRAPH-SERVICE
# spring.cloud.gateway.routes[2].predicates[0]=Path=/friendships/**

# spring.cloud.gateway.routes[3].id=contentService
# spring.cloud.gateway.routes[3].uri=lb://CONTENT-SERVICE
# spring.cloud.gateway.routes[3].predicates[0]=Path=/posts/**,/comments/**

# spring.cloud.gateway.routes[4].id=groupService
# spring.cloud.gateway.routes[4].uri=lb://GROUP-SERVICE
# spring.cloud.gateway.routes[4].predicates[0]=Path=/groups/**,/groupMembers/**

# spring.cloud.gateway.routes[5].id=messagingService
# spring.cloud.gateway.routes[5].uri=lb://MESSAGING-SERVICE
# spring.cloud.gateway.routes[5].predicates[0]=Path=/conversations/**,/conversationMembers/**,/conversationMessages/**

# spring.cloud.gateway.routes[6].id=eventService
# spring.cloud.gateway.routes[6].uri=lb://EVENT-SERVICE
# spring.cloud.gateway.routes[6].predicates[0]=Path=/events/**,/eventAttendees/** 