server.port=8087
spring.application.name=eventService

spring.datasource.url=jdbc:postgresql://postgres:5432/event_service_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false

management.metrics.enable.all=false
management.endpoints.enabled-by-default=false
management.metrics.use-global-registry=false
spring.jmx.enabled=false

spring.autoconfigure.exclude=\
org.springframework.boot.actuate.autoconfigure.metrics.MetricsAutoConfiguration,\
org.springframework.boot.actuate.autoconfigure.metrics.web.client.HttpClientMetricsAutoConfiguration,\
org.springframework.boot.actuate.autoconfigure.metrics.SystemMetricsAutoConfiguration,\

management.metrics.binders.processor.enabled=false
management.health.diskspace.enabled=false
management.health.livenessstate.enabled=false
management.health.readinessstate.enabled=false
spring.main.banner-mode=off 