server.port=8081
spring.application.name=auth-service

spring.datasource.url=jdbc:postgresql://postgres:5432/auth_service_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false

app.jwtSecret=KowalskiAnalysisCompletePenguinsOfMadagascarRicoKaboom
app.jwtExpirationInMs=90000