server.port=8085
spring.application.name=groupService

spring.datasource.url=jdbc:postgresql://localhost:5432/group_service_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true