server.port=8083
spring.application.name=socialGraphService

spring.datasource.url=jdbc:postgresql://postgres:5432/social_graph_service_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false